# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-vbD2bn0quASAIxpN8qZ9DXwgxtPPp3Y
"""

celsius = float(input('Enter temperature in °C: '))  
fahrenheit = (celsius * 9/5) + 32 
print("temperature in °F: ", fahrenheit)